### ISSUE TITLE
Unable to obtain URL for mode without Link member

### ISSUE THREAD

**Issue by sjsanjsrh** [hazre/ResoniteModUpdater#1]
It looks like the url is not defined or a database for the wrong mode is needed. (ex. [ReFract](https://github.com/pocoworks/ReFract)) For this purpose, a new repository or file may be needed.

**Comment by hazre** [comment]
> Updates mods that have that have a github Link variable.

There isn't much I can do. You have to get the mod author to add the Link variable to their mods for this to work. You should make a issue or pr on their  repository instead.

**Comment by sjsanjsrh** [comment]
I guess we can just parse discord's mod release channel?
