### ISSUE TITLE
[feature] use config file to store resonite location

### ISSUE THREAD

**Issue by Merith-TK** [hazre/ResoniteModUpdater#2]
So. I store resonite on my D:/ drive, since it is fast and means im not eating storage

I was hoping this tool could be setup to be an one-click and update *unless something goes wrong*

so maybe have an optional `ResoniteModUpdater.cfg` file next to it that just has an line for Resonite location?

**Comment by art0007i** [comment]
for the time being you can probably create a `ResoniteModUpdater.bat` which just runs the mod updater with whatever path you want, that way it can be single click too
